### ISSUE TITLE
Request - IIS Deploy - Do not purge everything each time.

### ISSUE THREAD

**Issue by alandillon** [TechnossusLLC/On-Premises-Release-Toolkit#12]
Ability to deploy an IIS Website without recreating the site and application pool each time.

So it just takes the site offline deletes files then deploys the new deployment package.

For example in cert we have passwords tied to the ApplicationPool user. 
Which we do not want to re-create every time.

**Comment by cwoolumtechnossus** [comment]
Hi Alan,

This task is only for Deploying IIS application configurations. It does not actually deploy the your code. You can do that from command line by calling the .CMD script generated by the publish.

Thanks,
Chris

Sent from Ninehttp://www.9folders.com/

**Comment by alandillon** [comment]
Ahhh ok. I thought you were creating something akin to this:  https://marketplace.visualstudio.com/items?itemName=ms-vscs-rm.iiswebapp

Got it! Thanks!

**Comment by cwoolumtechnossus** [comment]
Aaah, no. This was out before before that plugin was released. The biggest issue for me with that task is that you need to copy the files to the destination machine in order to deploy it. If you script it using a cmd task, it can run the command from the build server remotely.

It just depends on your preference and if you are running the deployment agent on your local network.

**Comment by alandillon** [comment]
Yeah I can understand that. I am using a UNC path at the moment. But I think I might switch to running the CMD.
